import mock from '../mock';

const knowledgeBaseDB = [	
	{
		id: '6',
		title: 'TERMS & CONDITIONS OF JOBSAGE',
		content: 
			`These are our terms of service, please take a moment to review all of these terms so you know what you're agreeing to, by clicking on accept and submit, we assume that you are agreeing to the following terms and conditions:
			In this Terms and Conditions, “we”, “us”, “our” or “Jobsage” refers to Jobsage LLP. located at 6064 Cloverdale, Dr Tega Cay, South Carolina, 29708.
			The following terms and conditions govern all use of the Jobsage website and all content, services and products available at or through the website, including, but not limited to, the jobsage product and jobsage hosted/cloud service (taken together, the Website). The Website is owned and operated by Jobsage. The Website is offered subject to your acceptance without modification of all of the terms and conditions contained herein and all other operating rules, policies (including, without limitation, Jobsage privacy policy) and procedures that may be published from time to time on this Site Jobsage.app (collectively, the "Agreement").
			Please read this Agreement carefully before accessing or using the Website. By accessing or using any part of the web site, you agree to become bound by the terms and conditions of this agreement. If you do not agree to all the terms and conditions of this agreement, then you may not access the Website or use any services. If these terms and conditions are considered an offer by Jobsage acceptance is expressly limited to these terms. The Website is available only to individuals who are at least 18 years old.
			Violation of any of the terms below will result in the termination of your Account. You agree to use the Service at your own risk.
			Our Customer Terms of Service is a contract that governs our Customers’ use of the Jobsage services. It consists of the following:
			• Master Terms: These contain the core legal and commercial terms that apply to your subscription to our product & services
			• Order form & Product Catalogue: These include any additional terms that apply to your use of each of our product & services offerings, our consulting and other services and third party services. 
			• Data Processing Agreement (DPA): This explains how we process your data and includes the EU Standard Contractual Clauses. 
			Your Order Form is the Jobsage-approved form created following your purchase of one of our products or services through our online payment process or via in-app purchase. It contains all of the details about your purchase, including your term, products & services purchased and your fees. You’ll find your Order Form(s) in the Documents section of your Jobsage portal. We’ve aimed to keep these documents as readable as possible, but in some cases for legal reasons, some of the language is necessarily “legalese”. By using the Service or receiving the Consulting Services, you are agreeing to these terms. We update these terms from time to time. If you have an active jobsage product or service usage, we will let you know when we update the terms via in-app notification or by email. You can find archived versions of the Master Terms, Product Specific Terms, Jurisdiction Specific Terms & DPA.
			MASTER TERMS
			1.DEFINITIONS 
			2.USE OF SERVICES 
			3.FEES 
			4.TERM & TERMINATION 
			5.CUSTOMER DATA 
			6.INTELLECTUAL PROPERTY 
			7.CONFIDENTIALITY 
			8.PUBLICITY 
			9.INDEMNIFICATION 
			10.DISCLAIMERS; LIMITATION OF LIABILITY 
			11.MISCELLANEOUS
			12.JURISDICTION
			
			1.DEFINITIONS:
			“Add-Ons” means additional product enhancements (including limit increases, capacity packs, and other add-ons) that are made available for purchase and are listed in the ‘Add-Ons and Technical Limits’ section of our Products and Services Catalog. 
			"Affiliate" means any entity which directly or indirectly controls, is controlled by, or is under common control with a party to this Agreement. For purposes of this definition, control means direct or indirect ownership or control of more than 50% of the voting interests of the subject entity. 
			"Agreement" or “Customer Terms of Service” means these Master Terms and all materials referred or linked to in here. 
			"Billing Period" means the period for which you agree to prepay fees under an Order Form. This may be the same length as than the service Term specified in your Order Form or it may be shorter. For example, if you subscribe to the Service for a one (1) year Subscription Term, with a twelve (12) month upfront payment, the Billing Period will be twelve (12) months. 
			“Confidential Information” means all confidential information disclosed by a party ("Disclosing Party") to the other party ("Receiving Party"), whether orally or in writing, that is designated as confidential. Confidential Information shall include all information concerning: (a) Disclosing Party's customers and potential customers, past, present or proposed products, marketing plans, engineering and other designs, technical data, business plans, business opportunities, finances, research, development, and the terms and conditions of this Agreement. Confidential Information does not include any information that (i) is or becomes generally known to the public without breach of any obligation owed to the Disclosing Party, (ii) was known to the Receiving Party prior to its disclosure by the Disclosing Party without breach of any obligation owed to the Disclosing Party, (iii) is received from a third party without breach of any obligation owed to the Disclosing Party, or (iv) was independently developed by the Receiving Party. Subject to the foregoing exclusions, Customer Data will be considered Confidential Information under this Agreement regardless of whether or not it is designated as confidential. 
			"Contact" means a single individual (other than a User) whose Contact Information is stored by you in the Service order form.
			"Contact Information" means the name, email address, phone number, online user name(s), telephone number, and similar information submitted by visitors to your landing pages on the Subscription Service or uploaded by you to the Subscription Service. "Consulting Services" means the professional services provided to you by us, which may include training services, installation, integration or other consulting services. 
			"Customer Data" means all information that you submit or collect via the Jobsage Service. Customer Data does not include Jobsage Content. 
			"Customer Materials" means all materials that you provide or post, upload, input or submit for public display through the Service.
			“DPA” means the Jobsage Data Processing Agreement.
			“Free Services” means the Service or other products or features made available by us to you on an unpaid trial or free basis.
			"Jobsage Content" means all information, data, text, messages, software, sound, music, video, photographs, graphics, images, and tags that we incorporate into the Subscription Service or Consulting Services, including Enrichment Data (as defined in the Product Specific Terms).
			"Order" or "Order Form" means the Jobsage-approved form or online subscription process by which you agree to subscribe to the Service and purchase Jobsage Consulting Services.
			“Personal Data” means any information relating to an identified or identifiable individual where such information is contained within Customer Data and is protected similarly as personal data or personally identifiable information under applicable Data Protection Law (as defined in the DPA).
			“Product and Services Catalog” means Jobsage’s Product and Services Catalog available at the website.
			“Product Specific Terms’ means the additional product-related terms that apply to your use of Jobsage products, our consulting services and Third party Services. These terms form part of the Agreement and can be found at the website.
			" Subscription Fees" means the amount you pay for the Jobsage Service excluding of all applicable taxes.
			"Subscription Service" means all of our web-based applications, tools and platforms that you have subscribed to under an Order Form or that we otherwise make available to you, and are developed, operated, and maintained by us, accessible via Jobsage.app or another designated URL, and any ancillary products and services, including website hosting, that we provide to you.
			"Subscription Term" means the initial term of your subscription to the applicable Subscription Service, as specified on your Order Form(s), and each subsequent renewal term (if any). For Free Services or trail period, the Subscription Term will be the period during which you have an account to access the Free Services or trial period.
			"Third-Party Products" means non-embedded products and professional services that are provided by third parties which interoperate with or are used in connection with the Subscription Service. These products and services include Non-Jobsage apps available.
			"Third-Party Sites" means third-party websites linked to from within the Subscription Service, including Communications Services.
			"Users" means your employees, representatives, consultants, contractors or agents who are authorized to use the Subscription Service for your benefit and have unique user identifications and passwords for the Subscription Service.
			"You", "your" or “Customer” means the person or entity using the Subscription Service or receiving the Consulting Services and identified in the applicable account record, billing statement, online subscription process, or Order Form as the customer.
			2.	USE OF SERVICES
			Access.  During the Subscription Term, we will provide your Users access to use the Subscription Service as described in this Agreement and the applicable Order. We may also provide your Users access to use our Free Services for trial period at any time by activating them . We might provide some or all elements of the Subscription Service through third party service providers. Your may provide access and use of the Subscription Service to your Affiliate’s Users or allow them to receive the Consulting Services purchased under this Order; provided that, all such access, use and receipt by your Affiliate’s Users is subject to and in compliance with the Agreement and you will at all times remain liable for your Affiliates' compliance with the Agreement. 
			Additional Features. You may subscribe to additional features of the Subscription Service by placing an additional Order or activating the additional features from within your Jobsage account (if this option is made available by us.). This Agreement will apply to all additional Order(s) and all additional features that you activate from within your HubSpot account. 
			Limits. The limits that apply to you will be specified in your Order Form, this Agreement or in our Product and Services Catalog, and for our Free Subscriptions, these limits may also be designated only from within the product itself. For further information on the limits that apply to your subscription, please refer to the Product Specific Terms in the product catalogue. You must be 18 years of age or older to use the Subscription Service. 
			Modifications. We modify the Subscription Service from time to time, including by adding or deleting features and functions, in an effort to improve your experience. For further information on our modification rights that apply to your subscription, please refer to the Product Specific Terms in the product catalogue 
			Customer Support. For information on the customer support terms that apply to your subscription, please refer the contact information on the website.
			Prohibited and Unauthorized Use. You will not use the Subscription Service in any way that violates the terms of the Acceptable use policy or for any purpose or in any manner that is unlawful or prohibited by this Agreement. You may not use the Subscription Service if you are legally prohibited from receiving or using the Subscription Service under the laws of the country in which you are resident or from which you access or use the Subscription Service. The Subscription Service is not designed to comply with industry-specific regulations such as the Health Insurance or the Federal Information etc., so you may not use the Subscription Service where your communications would be subject to such laws. Nothing contained in this section will limit the usage restrictions specific to Sensitive Information under the Agreement.
			No Sensitive Information. YOU ACKNOWLEDGE THAT THE SUBSCRIPTION SERVICES HAVE NOT BEEN DESIGNED TO PROCESS OR MANAGE SENSITIVE INFORMATION AND ACCORDINGLY YOU AGREE NOT TO USE THE SUBSCRIPTION SERVICE TO COLLECT, MANAGE OR PROCESS SENSITIVE INFORMATION. WE WILL NOT HAVE AND WE SPECIFICALLY DISCLAIM ANY LIABILITY THAT MAY RESULT FROM YOUR USE OF THE SUBSCRIPTION SERVICE TO COLLECT, PROCESS OR MANAGE SENSITIVE INFORMATION.
			3.FEES
			Subscription Fees. The Subscription Fee will remain fixed during the initial term of your subscription unless: (i) you exceed your Maximum resumes, Email Send Limit, User or other applicable limits (see the ‘Limits’ section above), (ii) you upgrade products or base packages, (iii) you subscribe to additional features or products, or (iv) otherwise agreed to in your Order. We may also choose to decrease your fees upon written notice to you. You can find all the information about how your fees may be otherwise adjusted in Product Specific Terms.
			Fee Adjustments at Renewal. Upon renewal, we may increase your fees up to our then current list price set out in our Product and Services Catalog. If this increase applies to you, we will notify you at least thirty (30) days in advance of your renewal and the increased fees will apply at the start of the next renewal term. If you do not agree to this increase, either party can choose to terminate your subscription at the end of your then-current term by giving the 30 days prior notice required.
			Payment by credit card. If you are paying by credit card, you authorize us to charge your credit card or bank account for all fees payable during the Subscription Term. You further authorize us to use a third party to process payments, and consent to the disclosure of your payment information to such third party.
			Payment against invoice. If you are paying by invoice, we will invoice you no more than thirty (30) days before the beginning of the Subscription Term and each subsequent Billing Period, and other times during the Subscription Term when fees are payable. All amounts invoiced are due and payable within thirty (30) days from the date of the invoice, unless otherwise specified in the Order Form.
			Payment Information. You will keep your contact information, billing information and credit card information (where applicable) up to date. Changes may be made on your Billing Page. All payment obligations are non-cancellable, and all amounts paid are non-refundable, except as specifically provided for in this Agreement. All fees are due and payable in advance throughout the Subscription Term. 
			Taxes. All fees are exclusive of taxes, which we will charge as applicable. You agree to pay any taxes applicable to your use of the Subscription Service and performance of Consulting Services. You will have no liability for any taxes based upon our gross revenues or net income. If you are located in the European Union, all fees are exclusive of any VAT and you represent that you are registered for VAT purposes in your member state. At our request, you will provide us with the VAT registration number under which you are registered in your member state. If you do not provide us with a VAT registration number prior to your transaction being processed, we will not issue refunds or credits for any VAT that was charged. If you are subject to GST, all fees are exclusive of GST.
			Withholding Tax. If you are required to deduct or withhold tax from payment of your Jobsage invoice, you may deduct this amount from the applicable Subscription Fee due to the extent it is due and payable as assessed withholding tax required under laws that apply to you (the “Deduction Amount”).
			You will not be required to repay the Deduction Amount to us, provided that you present us with a valid tax receipt verifying payment of the Deduction Amount to the relevant tax authority within ninety (90) days from the date of the invoice. If you do not provide this tax receipt within the specified time period, then all fees, inclusive of the Deduction Amount, will be immediately due and payable, and failure to pay these fees may result in your account being suspended or terminated for non-payment.
			4.TERM AND TERMINATION 
			Term and Renewal. Your initial subscription period will be specified in your Order, and, unless otherwise specified in your Order, your subscription will automatically renew for the shorter of the subscription period, or one year. 
			Notice of Non-Renewal. Unless otherwise specified in your Order, to prevent renewal of your subscription, you or we must give written notice of non-renewal. The deadline for sending this notice varies depending on the Jobsage product and edition you have subscribed to. For more information on non-renewal notice periods, please see the Product Specific Terms. If you decide not to renew, you may send this non-renewal notice to us by indicating that you do not want to renew.
			Early Cancellation. You may choose to cancel your subscription early at your convenience provided that, we will not provide any refunds of prepaid fees or unused Subscription Fees, and you will promptly pay all unpaid fees due through the end of the Subscription Term. 
			Termination for Cause. Either party may terminate this Agreement for cause, as to any or all Subscription Services: (i) upon thirty (30) days’ notice to the other party of a material breach if such breach remains uncured at the expiration of such period, or (ii) immediately, if the other party becomes the subject of a petition in bankruptcy or any other proceeding relating to insolvency, cessation of business, liquidation or assignment for the benefit of creditors. We may also terminate this Agreement for cause on thirty (30) days’ notice if we determine that you are acting, or have acted, in a way that has or may negatively reflect on or affect us, our prospects, or our customers. This Agreement may not otherwise be terminated prior to the end of the Subscription Term
			Suspension 
			Suspension for Prohibited Acts. We may suspend any User’s access to any or all Subscription Services without notice for: (i) use of the Subscription Service in a way that violates applicable local, state, federal, or foreign laws or regulations or the terms of this Agreement, (ii) use of the Jobsage email send service that results in excessive hard bounces, SPAM complaints via feedback loops, direct spam complaints (to our abuse desk), or requests for removal from a mailing list by recipients, or (iii) repeated instances of posting or uploading material that infringes or is alleged to infringe on the copyright or trademark rights of any person or entity. We may, without notice, review and delete any Customer Data or Customer Materials that we determine in good faith violate these terms or the AUP, provided that, we have no duty (unless applicable laws or regulations provide otherwise) to prescreen, control, monitor or edit your Customer Data or Customer Materials. 
			Suspension for Non-Payment. We will provide you with notice of non-payment of any amount due. Unless the full amount has been paid, we may suspend your access to any or all of the Subscription Services ten (10) days after such notice. We will not suspend the Subscription Service while you are disputing the applicable charges reasonably and in good faith and are cooperating diligently to resolve the dispute. If a Subscription Service is suspended for non-payment, we may charge a re-activation fee to reinstate the Subscription Service.
			 Suspension for Present Harm. If your website, or use of, the Subscription Service: (i) is being subjected to denial of service attacks or other disruptive activity, (ii) is being used to engage in denial of service attacks or other disruptive activity, (iii) is creating a security vulnerability for the Subscription Service or others, (iv) is consuming excessive bandwidth, or (v) is causing harm to us or others, then we may, with electronic or telephonic notice to you, suspend all or any access to the Subscription Service. 
			Suspension and Termination of Free Services. We may suspend, limit, or terminate the Free Services for any reason at any time without notice. We may terminate your subscription to the Free Services due to your inactivity. 
			Effect of Termination or Expiration. Upon termination or expiration of this Agreement, you will stop all use of the Subscription Service and Jobsage Content. If you terminate this Agreement for cause of material breach, we will promptly refund any prepaid but unused fees covering use of the Subscription Service after termination. If we terminate this Agreement for cause of material breach, you will promptly pay all unpaid fees due through the end of the Subscription Term. Fees which are otherwise non-refundable.
			5.CUSTOMER DATA 
			Customer’s Proprietary Rights. You own and retain all rights to the Customer Materials and Customer Data. This Agreement does not grant us any ownership rights to Customer Materials or Customer Data. You grant permission to us and our licensors to use the Customer Materials and Customer Data only as necessary to provide the Subscription Service and Consulting Services to you and as otherwise permitted by this Agreement. If you are using the Subscription Service or receiving Consulting Services on behalf of another party, then you represent and warrant that you have all sufficient and necessary rights and permissions to do so.
			We may monitor use of the Subscription Service by all of our customers and use the information gathered in an aggregate and anonymized manner. We may use Customer Data in an anonymized manner for machine learning. 
			Protection of Customer Data. The terms of the DPA are hereby incorporated by reference and will apply to the extent any Customer Data includes Personal Data. The DPA sets out how we will process Personal Data on your behalf in connection with the Subscription Services provided to you under this Agreement. We will maintain commercially appropriate administrative, physical, and technical safeguards to protect Personal Data.
			6.INTELLECTUAL PROPERTY
			This is an agreement for access to and use of the Subscription Service, and you are not granted a license to any software by this Agreement. The Subscription Service and Consulting Services are protected by intellectual property laws, they belong to and are the property of us or our licensors (if any), and we retain all ownership rights to them. You agree not to copy, rent, lease, sell, distribute, or create derivative works based on the HubSpot Content, the Subscription Service, or the Consulting Services in whole or in part, by any means, except as expressly authorized in writing by us. Our trademarks include, but aren’t limited to, those listed at jobsage website (which we may update at any time without notice to you) and you may not use any of these without our prior written permission.
			7.PUBLICITY 
			You grant us the right to add your name and company logo to our customer list and website.
			
			
			8.CONFIDENTIALITY
			The Receiving Party will: (i) protect the confidentiality of the Confidential Information of the Disclosing Party using the same degree of care that it uses to protect the confidentiality of its own confidential information of like kind, but in no event less than reasonable care, (ii) not use any Confidential Information of the Disclosing Party for any purpose outside the scope of this Agreement, (iii) not disclose Confidential Information of the Disclosing Party to any third party (except those third party service providers used by us to provide some or all elements of the Subscription Service or Consulting Services 
			The Receiving Party may disclose Confidential Information of the Disclosing Party if required to do so under any federal, state, or local law, statute, rule or regulation, subpoena or legal process; provided, however, that (i) the Receiving Party will provide the Disclosing Party with prompt notice of any request that it disclose Confidential Information, sufficient to allow the Disclosing Party to object to the request and/or seek an appropriate protective order or, if such notice is prohibited by law, the Receiving Party will disclose the minimum amount of Confidential Information required to be disclosed under the applicable legal mandate; and (ii) in no event will the Receiving Party disclose Confidential Information to a party other than a government agency except under a valid order from a court having jurisdiction requiring the specific disclosure.
			9.INDEMNIFICATION 
			You will indemnify, defend and hold us and our Affiliates harmless, at your expense, against any third-party claim, suit, action, or proceeding (each, an "Action") brought against us (and our officers, directors, employees, agents, service providers, licensors, and affiliates) by a third party not affiliated with us or our Affiliates to the extent that such Action is based upon or arises out of (a) unauthorized or illegal use of the Subscription Service by you or your Affiliates, (b) your or your Affiliates' noncompliance with or breach of this Agreement, (c) your or your Affiliates' use of Third-Party Products, or (d) the unauthorized use of the Subscription Service by any other person using your User information. We will: notify you in writing within thirty (30) days of our becoming aware of any such claim; give you sole control of the defense or settlement of such a claim; and provide you (at your expense) with any and all information and assistance reasonably requested by you to handle the defense or settlement of the claim. You will not accept any settlement that (i) imposes an obligation on us; (ii) requires us to make an admission; or (iii) imposes liability not covered by these indemnifications or places restrictions on us without our prior written consent.
			10.DISCLAIMERS; LIMITATION OF LIABILITY 
			Disclaimer of Warranties. WITHOUT LIMITING OUR OBLIGATIONS IN THE 'PROTECTION OF CUSTOMER DATA' SECTION OF THIS AGREEMENT, WE AND OUR AFFILIATES AND AGENTS MAKE NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY, RELIABILITY, AVAILABILITY, TIMELINESS, SECURITY OR ACCURACY OF THE SUBSCRIPTION SERVICE, DATA MADE AVAILABLE FROM THE SUBSCRIPTION SERVICE, HUBSPOT CONTENT, OR THE CONSULTING SERVICES FOR ANY PURPOSE.. TO THE EXTENT PERMITTED BY LAW, THE SUBSCRIPTION SERVICE, JOBSAGE CONTENT AND CONSULTING SERVICES ARE PROVIDED "AS IS" WITHOUT WARRANTY OR CONDITION OF ANY KIND. WE DISCLAIM ALL WARRANTIES AND CONDITIONS OF ANY KIND, WHETHER EXPRESS, IMPLIED OR STATUTORY, WITH REGARD TO THE SUBSCRIPTION SERVICE AND THE CONSULTING SERVICES, INCLUDING ALL IMPLIED WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. 
			No Indirect Damages. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT WILL EITHER PARTY OR ITS AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES, OR LOSS OF PROFITS, REVENUE, DATA OR BUSINESS OPPORTUNITIES ARISING OUT OF OR RELATED TO THIS AGREEMENT, WHETHER AN ACTION IS IN CONTRACT OR TORT AND REGARDLESS OF THE THEORY OF LIABILITY; PROVIDED THAT.
			Limitation of Liability. EXCEPT FOR YOUR LIABILITY FOR PAYMENT OF FEES, YOUR LIABILITY ARISING FROM YOUR OBLIGATIONS UNDER THE ‘INDEMNIFICATION’ SECTION, AND YOUR LIABILITY FOR VIOLATION OF OUR INTELLECTUAL PROPERTY RIGHTS, IF, NOTWITHSTANDING THE OTHER TERMS OF THIS AGREEMENT, EITHER PARTY OR ITS AFFILIATES IS DETERMINED TO HAVE ANY LIABILITY TO THE OTHER PARTY, ITS AFFILIATES OR ANY THIRD PARTY, THE PARTIES AGREE THAT THE AGGREGATE LIABILITY OF A PARTY AND ITS AFFILIATES WILL BE LIMITED TO A SUM EQUAL TO THE TOTAL AMOUNTS PAID OR PAYABLE FOR THE SUBSCRIPTION SERVICE IN THE TWELVE MONTH PERIOD PRECEDING THE EVENT GIVING RISE TO A CLAIM; PROVIDED HOWEVER, THIS LIMITATION WILL NOT APPLY TO YOU IF YOU ONLY USE THE FREE SERVICES, AND IN THIS CASE, IF WE ARE DETERMINED TO HAVE ANY LIABILITY TO YOU OR ANY THIRD PARTY ARISING FROM YOUR USE OF THE FREE SERVICES, THEN OUR AGGREGATE LIABILITY WILL BE LIMITED TO ONE HUNDRED U.S. DOLLARS. 
			Third Party Products. WE AND OUR AFFILIATES DISCLAIM ALL LIABILITY WITH RESPECT TO THIRD-PARTY PRODUCTS THAT YOU USE. OUR LICENSORS WILL HAVE NO LIABILITY OF ANY KIND UNDER THIS AGREEMENT. 
			Agreement to Liability Limit. YOU UNDERSTAND AND AGREE THAT ABSENT YOUR AGREEMENT TO THIS LIMITATION OF LIABILITY, WE WOULD NOT PROVIDE THE SUBSCRIPTION SERVICE TO YOU.
			11.MISCELLANEOUS
			Force Majeure. Neither party will be responsible for failure or delay of performance if caused by: an act of war, hostility, or sabotage; act of God; electrical, internet, or telecommunication outage that is not caused by the obligated party; government restrictions; or other event outside the reasonable control of the obligated party. Each party will use reasonable efforts to mitigate the effect of a force majeure event.
			Actions Permitted. Except for actions for non-payment or breach of a party’s proprietary rights, no action, regardless of form, arising out of or relating to this Agreement may be brought by either party more than one (1) year after the cause of action has accrued.
			Relationship of the Parties. You and we agree that no joint venture, partnership, employment, or agency relationship exists between us.
			Compliance with Laws. We will comply with all United States Federal & State laws (where applicable) in our provision of the Subscription Service, the Consulting Services and our processing of Customer Data. We reserve the right at all times to disclose any information as necessary to satisfy any law, regulation, legal process or governmental request, You will not directly or indirectly export, re-export, or transfer the Subscription Service or Consulting Services to prohibited countries or individuals or permit use of the Subscription Service or Consulting Services by prohibited countries or individuals.
			Severability. If any part of this Agreement or an Order Form is determined to be invalid or unenforceable by applicable law, then the invalid or unenforceable provision will be deemed superseded by a valid, enforceable provision that most closely matches the intent of the original provision and the remainder of this Agreement will continue in effect.
			Notice will be sent to the contact address set forth in the Jurisdiction Specific Terms and will be deemed delivered as of the date of actual receipt.
			This Agreement (including each Order), along with our Privacy Policy is the entire agreement between us for the Subscription Service and Consulting Services and supersedes all other proposals and agreements, whether electronic, oral or written, between us. We object to and reject any additional or different terms proposed by you, including those contained in your purchase order, acceptance or website. Our obligations are not contingent on the delivery of any future functionality or features of the Subscription Service or dependent on any oral or written public comments made by us regarding future functionality or features of the Subscription Service. We might make versions of this Agreement available in languages other than English. If we do, the English version of this Agreement will govern our relationship and the translated version is provided for convenience only and will not be interpreted to modify the English version of this Agreement.
			No Third Party Beneficiaries. Nothing in this Agreement, express or implied, is intended to or will confer upon any third party person or entity any right, benefit or remedy of any nature whatsoever under or by reason of this Agreement.
			Authority. Each party represents and warrants to the other that it has full power and authority to enter into this Agreement and that it is binding upon such party and enforceable in accordance with its terms. You further warrant and represent that you have has the authority to procure your Affiliates compliance with the terms of this Agreement.
			Precedence. In the event of a conflict between the terms of the Agreement and an Order, the terms of the Order will control, but only as to that Order.
			12.JURISDICTION
			This Agreement constitutes the entire agreement between Jobsage and you concerning the subject matter hereof, and they may only be modified by a written amendment signed by an authorized executive of Jobsage, or by the posting by Jobsage of a revised version. The Agreement and these Conditions shall be governed by and construed in accordance with the applicable laws of United States & by the laws of the state of South Carolina. Unless any alternative dispute resolution procedure is agreed between the parties, the parties agree to submit to the exclusive jurisdiction of the Federal Courts in South Carolina & laws of United states in respect of any dispute which arises out of or under this Agreement. The prevailing party in any action or proceeding to enforce this Agreement shall be entitled to costs and attorneys' fees. If any part of this Agreement is held invalid or unenforceable, that part will be construed to reflect the parties' original intent, and the remaining portions will remain in full force and effect. A waiver by either party of any term or condition of this Agreement or any breach thereof, in any one instance, will not waive such term or condition or any subsequent breach thereof. You may assign your rights under this Agreement to any party that consents to, and agrees to be bound by, its terms and conditions; Jobsage may assign its rights under this Agreement without condition. This Agreement will be binding upon and will inure to the benefit of the parties, their successors and permitted assigns.
			JOBSAGE DATA PROCESSING AGREEMENT (DPA)
			CUSTOMER RESPONSIBILITIES 
			Compliance with Laws. Within the scope of the Agreement and in its use of the services, you will be responsible for complying with all requirements that apply to it under applicable Data Protection Laws with respect to its Processing of Personal Data and the Instructions it issues to us. In particular but without prejudice to the generality of the foregoing, you acknowledge and agree that you will be solely responsible for: (i) the accuracy, quality, and legality of Customer Data and the means by which you acquired Personal Data; (ii) complying with all necessary transparency and lawfulness requirements under applicable Data Protection Laws for the collection and use of the Personal Data, including obtaining any necessary consents and authorizations (particularly for use by Customer for marketing purposes); (iii) ensuring you have the right to transfer, or provide access to, the Personal Data to us for Processing in accordance with the terms of the Agreement (including this DPA); (iv) ensuring that your Instructions to us regarding the Processing of Personal Data comply with applicable laws, including Data Protection Laws; and (v) complying with all laws (including Data Protection Laws) applicable to any emails or other content created, sent or managed through the Subscription Services, including those relating to obtaining consents (where required) to send emails, the content of the emails and its email deployment practices. You will inform us without undue delay if it is not able to comply with its responsibilities.
			Controller Instructions. The parties agree that the Agreement (including this DPA), together with your use of the Subscription Service in accordance with the Agreement, constitute your complete and final Instructions to us in relation to the Processing of Personal Data, and additional instructions outside the scope of the Instructions shall require prior written agreement between us and you.
			JOBSAGE OBLIGATIONS 
			Compliance with Instructions. We will only Process Personal Data for the purposes described in this DPA or as otherwise agreed within the scope of your lawful Instructions, except where and to the extent otherwise required by applicable law. We are not responsible for compliance with any Data Protection Laws applicable to you or your industry that are not generally applicable to us. 
			Conflict of Laws. If we become aware that we cannot Process Personal Data in accordance with your Instructions due to a legal requirement under any applicable law, we will (i) promptly notify you of that legal requirement to the extent permitted by the applicable law; and (ii) where necessary, cease all Processing (other than merely storing and maintaining the security of the affected Personal Data) until such time as you issue new Instructions with which we are able to comply. If this provision is invoked, we will not be liable to you under the Agreement for any failure to perform the applicable Subscription Services until such time as you issue new lawful Instructions with regard to the Processing.
			Security. We will implement and maintain appropriate technical and organizational measures to protect Personal Data from Personal Data Breaches,. Notwithstanding any provision to the contrary, we may modify or update the Security Measures at our discretion provided that such modification or update does not result in a material degradation in the protection offered by the Security Measures. 
			Confidentiality. We will ensure that any personnel whom we authorize to Process Personal Data on our behalf is subject to appropriate confidentiality obligations (whether a contractual or statutory duty) with respect to that Personal Data. 
			Personal Data Breaches. We will notify you without undue delay after it becomes aware of any Personal Data Breach and will provide timely information relating to the Personal Data Breach as it becomes known or reasonably requested by you. At your request, we will promptly provide you with such reasonable assistance as necessary to enable you to notify relevant Personal Data Breaches to competent authorities and/or affected Data Subjects, if you are required to do so under Data Protection Laws. 
			Deletion or Return of Personal Data. We will delete or return all Customer Data, including Personal Data upon termination or expiration of your Subscription Service in accordance with the procedures and timeframes set out in the Agreement, save that this requirement shall not apply to the extent we are required by applicable law to retain some or all of the Customer Data, or to Customer Data it has archived on back-up systems, which data we will securely isolate and protect from any further Processing and delete in accordance with its deletion practices. You may request the deletion of your HubSpot account after expiration or termination of your subscription by sending a request here or by following the instructions found here. You may retrieve your Customer Data from your account in accordance with our ‘Retrieval of Customer Data’ sections throughout our Product Specific Terms.
			Sub-Processors. You agree that we may engage Sub-Processors to Process Personal Data on your behalf. we will impose data protection terms on the SubProcessors that provide at least the same level of protection for Personal Data as those in this DPA. We will remain responsible for each Sub-Processor’s compliance with the obligations of this DPA.
			Data Transfers 
			You acknowledge and agree that we may access and Process Personal Data on a global basis as necessary to provide the Subscription Service in accordance with the Agreement, and in particular that Personal Data will be transferred to and Processed by Jobsage. in India & US and to other jurisdictions where Jobsage Affiliates and Sub-Processors have operations. We will ensure such transfers are made in compliance with the requirements of Data Protection Laws.
			PARTIES TO THIS DPA 
			Permitted Affiliates. By accepting this Agreement, you enter into this DPA on behalf of yourself and, to the extent required under applicable Data Protection Laws, in the name and on behalf of your Permitted Affiliates, thereby establishing a separate DPA between us and each such Permitted Affiliate subject to the Agreement and the ‘General Provisions’ and ‘Parties to this DPA’ sections of this DPA. Each Permitted Affiliate agrees to be bound by the obligations under this DPA and, to the extent applicable, the Agreement. For the purposes of this DPA only, and except where indicated otherwise, the terms “Customer”, “you” and “your” will include you and such Permitted Affiliates.
			Authorization. The legal entity agreeing to this DPA as Customer represents that it is authorized to agree to and enter into this DPA for and on behalf of itself and, as applicable, each of its Permitted Affiliates.
			Remedies. Except where applicable Data Protection Laws require a Permitted Affiliate to exercise a right or seek any remedy under this DPA against us directly by itself, the parties agree that (i) solely the Customer entity that is the contracting party to the Agreement will exercise any right or seek any remedy any Permitted Affiliate may have under this DPA on behalf of its Affiliates, and (ii) the Customer entity that is the contracting party to the Agreement will exercise any such rights under this DPA not separately for each Permitted Affiliate individually but in a combined manner for itself and all of its Permitted Affiliates together. The Customer entity that is the contracting entity is responsible for coordinating all communication with us under the DPA and will be entitled to make and receive any communication related to this DPA on behalf of its Permitted Affiliates. 
			Other rights. The parties agree that you will, when reviewing our compliance with this DPA pursuant to the ‘Demonstration of Compliance’ section, take all reasonable measures to limit any impact on us and our Affiliates by combining several audit requests carried out on behalf of the Customer entity that is the contracting party to the Agreement and all of its Permitted Affiliates in one single audit.			
			`
	},
	{
		id: '7',
		title: 'PRIVACY & POLICY OF JOBSAGE',
		content: 		
		`Effective: 01st May, 2021
		INTRODUCTION:
		1.We are committed to safeguarding the privacy of our service users.
		2.This policy applies where we are acting as a data controller with respect to the personal data of our service users; in other words, where we determine the purposes and means of the processing of that personal data.
		1.“Personal Data” is any information that relates to an identified or identifiable living individual. Different pieces of information, which collected together can lead to the identification of a particular person, also constitute personal data.
		3.We use cookies on our website. Insofar as those cookies are not strictly necessary for the provision of our website and services, we will ask you to consent to our use of cookies when you first visit our website.
		4.In this policy, “we”, “us”, “our” or “Jobsage” refers to Jobsage LLP. located at 6064 Cloverdale, Dr Tega Cay, South Carolina, 29708.
		5.Jobsage LLP. is a LLP registered under the provincial laws of South Carolina, United States. This Privacy Policy refers to all websites that we own and operate, including the websites located at jobsage.app and all related websites, our applications and/or APIs, and online services (our “Website”), as well as our other services, offerings, and other interactions (e.g., customer service inquiries, user collaborations, etc.) you may have with us (together with our Website, collectively referred to as our “Services”). If you do not agree with the data practices described in this Privacy Policy, you should not use our Services. This Privacy Policy does not apply to any third party applications or software that integrate with the Services through our Website (“Third Party Services”), or any other third party products, services or businesses.
		6.All the personal data collected is stored on secure servers. Unfortunately, the transmission of information via the internet is not completely secure. Although we will take reasonable commercial effort to protect Your personal data, we cannot guarantee the complete security of Your data transmitted to the Website and therefore any transmission is at Your own risk. Once we have received Your information, we will use strict procedures and security features to try to prevent unauthorized access.
		
		SOURCES OF DATA
		1.Jobsage generally collects, uses and discloses personal information about the following types of individuals:
		1.Customers;
		2.Consultants;
		3.Other individuals who may voluntarily choose to provide Jobsage with personal information; and/or
		4.Data collected from third parties that we did not obtain directly from you.
		
		HOW WE WILL PROCESS AND COLLECT YOUR DATA
		1.In this Section we have set out:
		1.the general categories of personal data that we may collect;
		2.In the case of personal data that we did not obtain directly from you, the source and specific categories of that data; and,
		3.the purposes for which we may process personal data; and the legal bases of the processing.
		2.We may process your account data (“Account Data”). The source of the account data is you, or an alienate data service. The account data may be processed for the purposes of operating our website, providing our services, ensuring the security of our website and services, maintaining back-ups of our databases and communicating with you. The legal basis for this processing is consent OR our legitimate interests, namely the proper administration of our website and service and business OR the performance of a contract between you and us and/or taking steps, at your request, to enter into such a contract OR refine our Service through automated data processing.
		3.We may process your information included in your personal profile on our website (“Profile Data”). The profile data may include your name, company name, address, telephone number, email address, profile pictures, website, social handles, gender, date of birth, interests and hobbies, confidential business information, marketing targets, educational details and employment details. The Profile Data may be processed for the purposes of enabling and monitoring your use of our website and the services. The legal basis for this processing is consent OR our legitimate interests, namely the proper administration of our website and business OR the performance of a contract between you and us and/or taking steps, at your request, to enter into such a contract.
		4.We may process your personal data that is provided in the course of the use of our services (“Service Data”). You are the source of the service data that we use. The service data may be processed for the purposes of operating our website, providing our services, ensuring the security of our website and services, service accuracy, maintaining back-ups of our databases and communicating with you. The legal basis for this processing is consent OR our legitimate interests, namely the proper administration and utilization of our website and business OR the performance of a contract between you and us and/or taking steps, at your request, to enter into such a contract.
		5.We may process Information contained in any inquiry you submit to us regarding services (“Inquiry Data”). The Inquiry Data may be processed for the purposes of offering, marketing and selling relevant services to you. The legal basis for this processing is consent.
		6.We may process information relating to our client relationships, including client contact information] (“Client Relationship Data”). The Client Relationship Data may include your name, your employer or company name, your job title or role, industry, location, marketing targets, your contact details, and information contained in communications between us and you or your employer. The source of the client relationship data is you or your employer. The Client Relationship Data may be processed for the purposes of managing our relationships with clients, communicating with clients, keeping records of those communications and our services to clients. The legal basis for this processing is consent OR our legitimate interests, namely the proper management of our client relationships.
		7.We may process information contained in or relating to any communication that you send to us and any information contained in any linked e-mail accounts (“Correspondence Data” or “Message Data”). The Correspondence Data may include the communication content and metadata associated with the communication. Our website will generate the metadata associated with communications made using the website contact forms and any other automated means. The Correspondence Data may be processed for the purposes of communicating with you and record-keeping. The legal basis for this processing is our legitimate interests, namely the proper administration of our website and business and communications with clients OR improving our services.
		8.We may process any of your personal data identified in this policy where necessary for the establishment, exercise or defence of legal claims, whether in court proceedings or in an administrative or within any out-of-court procedure such as mediation or arbitration. The legal basis for this processing is our legitimate interests, namely the protection and assertion of our legal rights, your legal rights and the legal rights of others.
		9.We may process any of your personal data identified in this policy where necessary for the purposes of obtaining or maintaining insurance coverage, managing risks, or obtaining professional advice. The legal basis for this processing is our legitimate interests, namely the proper protection of our business against risks.
		10.In addition to the specific purposes for which we may process your personal data set out in this Section, we may also process any of your personal or business data where such processing is necessary for compliance with a legal obligation to which we are subject, or in order to protect your vital interests or the vital interests of another natural person.
		11.Please do not supply any other person’s personal data to us, unless we prompt you to do so within our platform.
		
		HOW WE WILL USE YOUR DATA
		1.We may use the Personal Information collected by us in the following manner:
		
		1.Monitor the use of the Website for the technical administration of the AKP Solutions, Experts Connect or Jobsage websites;
		2.Use cookies to better understand how You interact with the Website, to monitor aggregate usage by the users and web traffic routing on the Website, and to improve the Website and the Website; and
		3.Use Personal Information, to conduct research and for further development of our services in order to provide You with a better, more intuitive and personalized experience.
		4.to establish and manage client relationships, fulfill duties, and avoid conflicts of interest;
		5.to establish and maintain commercial relationships with clients, suppliers, service providers and other third parties;
		6.to establish, manage and terminate contractual and partnership relationships;
		7.to conduct surveys, research and evaluations;
		8.to develop, enhance, market, sell or otherwise provide Jobsage products and services;
		9.to market, sell or otherwise provide products and services of third parties with whom we have a commercial relationship;
		10.to distribute our newsletters and other informational e-mail communications and other material to individuals on our mail and e-mail lists;
		11.to develop and manage our business and operations;
		12.to detect and protect Jobsage and other third parties against error, negligence, breach of contract, fraud, theft and other illegal activity;
		13.to audit compliance with our policies and contractual obligations;
		14.as permitted by, and to comply with, any legal or regulatory requirements or provisions; and
		15.for any other purpose to which you consent.
		
		PROVIDING YOUR PERSONAL DATA TO OTHERS
		1.We do not disclose your personal and business data to any third-party other than what is stated in this Section.
		2.We may disclose your personal, marketing, and business data to our insurers and/or professional advisers insofar as reasonably necessary for the purposes of obtaining or maintaining insurance coverage, managing risks, obtaining professional advice, or the establishment, exercise or defence of legal claims, whether in court proceedings or in an administrative or out-of-court procedure.
		3.We may disclose personal, marketing, and business data to our IT suppliers or subcontractors insofar as reasonably necessary for the services provided by Jobsage LLP.
		4.In addition to the specific disclosures of personal data set out in this Section, we may disclose your personal data where such disclosure is necessary for compliance with a legal obligation to which we are subject, or in order to protect your vital interests or the vital interests of another natural person. We may also disclose your personal data where such disclosure is necessary for the establishment, exercise or defense of legal claims, whether in court proceedings or in an administrative or out-of-court procedure.
		1.In case that we will be under a duty to disclose or share Your personal data with or without Your consent, and with or without notice in order to comply with any legal obligation, including without limitation a subpoena, court order, or search warrant.
		
		RETAINING AND USE OF PERSONAL DATA
		1.This Section sets out our data retention policies and procedures, which are designed to help ensure that we comply with our legal obligations in relation to the retention and deletion of personal data.
		2.Personal data that we process may be stored for a period of time after you no longer use our website. The personal data stored for any purpose or purposes shall not be kept for longer than is necessary for that purpose or those purposes.
		3.The time periods for which we retain your information depends on the type of information and the purposes for which we use it. We will keep your information for no longer than is required or permitted.
		1.For further clarity, we may also retain your personal data where such retention is necessary for compliance with a legal obligation to which we are subject, or in order to protect your vital interests or the vital interests of another natural person.
		
		NOTIFICATIONS AND CONSENT
		1.Subject to this Policy and applicable legislation, Jobsage will identify the purposes for collection, use and disclosure in advance of collection, and will notify the individual of the purposes for collection, use or disclosure at or before the time of collection.
		2.Jobsage will generally obtain consent from the individual at or before the time of collection of personal information.  However, there are a number of exceptions in that in some circumstances, such as with employee personal information, Jobsage does not require consent to collect, use or disclose personal information with respect to employees, but may be required to provide notification in advance.
		3.In other circumstances, specifically those set out in applicable legislation, the law does not require that Jobsage obtain consent or provide notification. Jobsage reserves all its rights to rely on all available statutory exemptions and exceptions.
		
		EXPRESS CONSENT
		1.Online Communications. You may voluntarily submit Personal Information to us for purposes such as asking a question, obtaining information, reviewing or downloading a publication, subscribing to a newsletter or a mail or e-mail list, participating in a seminar or other event, and participating in contests and surveys. If you are a registered user of an online service on our website, we may combine and store Personal Information about your use of our website and information you have provided to us with certain other online and offline information we may have collected.
		2.E-mail Communications. We may send you marketing or promotional e-mail communications. In this process, we may collect certain information such as the date and time you first opened our e-mail communications, the number of times you open our e-mail communications, the number of instances you click through our articles and your total click-through activity on the contents of our e-mail communications. We may also combine and store any such information to manage and improve our e-mail communications. If you no longer wish to receive any future marketing or promotional material from us, our promotional e-mail communications will include instructions on how to unsubscribe and inform us of your preferences.
		3.Third Party Websites. We may include links to other websites on our website. These third party websites may collect your Personal Information and they may have different privacy policies and practices than Jobsage. We do not assume any responsibility for the privacy practices, policies or actions of the third parties operating these websites. We strongly encourage you to read the privacy policies of these websites to enable you to make an informed decision whether or not to provide your Personal Information to the websites’ operators.
		
		US ANTI-SPAM COMPLIANCE
		1.US has implemented legislation (Generally referred to as US Anti-Spam Legislation) prohibiting commercial electronic communications without adequate consent, and without an adequate unsubscribe mechanism.  Commercial electronic communications (“CEMs”) are defined as emails and text messages. It is the policy of Jobsage to not send CEMs without valid legal consent from the recipient, and it is the policy of Jobsage to always use the unsubscribe mechanisms prescribed by US Anti Spam legislations.
		
		AMENDMENTS
		1.We may update this policy from time to time for any reason by publishing a new version on our website. Each version will apply to information collected while it was in place.
		2.You should check this page occasionally to ensure you are satisfied with any changes to this policy.
		
		YOUR RIGHTS
		1.In this Section, we have summarized the rights that you have under data protection law. Some of the rights are complex, and not all of the details have been included in our summaries. Accordingly, you should read the relevant laws and guidance from the regulatory authorities for a full explanation of these rights.
		
		2.Your principal rights under data protection law are:
		1.the right to access;
		2.the right to rectification;
		3.the right to erasure;
		4.the right to restrict processing;
		5.the right to object to processing;
		6.the right to data portability;
		7.the right to complain to a supervisory authority; and,
		8.the right to withdraw consent.
		
		3.You have the right to confirm as to whether or not we process your personal data and, where we do, access to the personal data, together with certain additional information. That additional information includes details of the purposes of the processing, the categories of personal data concerned and the recipients of the personal data. Providing the rights and freedoms of others are not affected, we will supply to you a copy of your personal data. The first copy will be provided free of charge, but additional copies may be subject to a reasonable fee.
		
		4.You have the right to have any inaccurate personal data about you rectified and, taking into account the purposes of the processing, to have any incomplete personal data about you completed.
		5.In some circumstances you have the right to the erasure of your personal data without undue delay. Those circumstances include:
		1.The personal data are no longer necessary in relation to the purposes for which they were collected or otherwise processed; you withdraw consent to consent-based processing; you object to the processing under certain rules of applicable data protection law; the processing is for direct marketing purposes; and the personal data have been unlawfully processed.
		2.However, there are exclusions of the right to erasure. The general exclusions include where processing is necessary:
		1.For exercising the right of freedom of expression and information
		2.For compliance with a legal obligation; or,
		3.For the establishment, exercise or defence of legal claims.
		6.In some circumstances you have the right to restrict the processing of your personal data. Those circumstances are: you contest the accuracy of the personal data; processing is unlawful but you oppose erasure; we no longer need the personal data for the purposes of our processing, but you require personal data for the establishment, exercise or defence of legal claims; and you have objected to processing, pending the verification of that objection. Where processing has been restricted on this basis, we may continue to store your personal data. However, we will only otherwise process it: with your consent; for the establishment, exercise or defence of legal claims; for the protection of the rights of another natural or legal person; or for reasons of important public interest.
		7.You have the right to object to our processing of your personal data on grounds relating to your particular situation, but only to the extent that the legal basis for the processing is that the processing is necessary for: the performance of a task carried out in the public interest or in the exercise of any official authority vested in us; or the purposes of the legitimate interests pursued by us or by a third party. If you make such an objection, we will cease to process the personal information unless we can demonstrate compelling legitimate grounds for the processing which override your interests, rights and freedoms, or the processing is for the establishment, exercise or defence of legal claims.
		8.You have the right to object to our processing of your personal data for direct marketing purposes (including profiling for direct marketing purposes) towards you. If you make such an objection, we will cease to process your personal data for this purpose. However, if this objection impedes the quality of our services for you, you understand and agree that our service effectiveness will be impeded and you may have to cease using our service.
		9.You have the right to object to our processing of your personal data for scientific or historical research purposes or statistical purposes on grounds relating to your particular situation, unless the processing is necessary for the performance of a task carried out for reasons of public interest.
		10.To the extent that the legal basis for our processing of your personal data is:
		1.Consent; or,
		2.that the processing is necessary for the performance of a contract to which you are party or in order to take steps at your request prior to entering into a contract, and such processing is carried out by automated means, you have the right to receive your personal data from us in a structured, commonly used and machine-readable format. However, this right does not apply where it would adversely affect the rights and freedoms of others.
		11.If you consider that our processing of your personal information infringes data protection laws, you have a legal right to lodge a complaint with relevant supervisory authority responsible for data protection. Specifically,
		1.If you are a resident of the United States, you may file a complaint with the Federal Trade Commission (FTC) or any other relevant Federal or State body; or,
		2.If you are a resident of Canada, you may file a complaint with the Canadian Office of the Privacy Commissioner or any other relevant Federal or Provincial body;
		3.If you are a resident of the European Union or European Economic Area, you may do so in the EU/EEA member state of your habitual residence, your place of work or the place of the alleged infringement.
		4.To the extent that the legal basis for our processing of your personal information is consent, you have the right to withdraw that consent at any time. Withdrawal will not affect the lawfulness of processing before the withdrawal.
		5.You may exercise any of your rights in relation to your personal data by written notice to us.
		COOKIES AND TRACKING
		1.A cookie is a file containing an identifier (a string of letters and numbers) that is sent by a web server to a web browser and is stored by the browser. The identifier is then sent back to the server each time the browser requests a page from the server.
		2.Cookies may be either “persistent” cookies or “session” cookies: a persistent cookie will be stored by a web browser and will remain valid until its set expiry date, unless deleted by the user before the expiry date; a session cookie, on the other hand, will expire at the end of the user session, when the web browser is closed.
		3.Cookies do not typically contain any information that personally identifies a user, but personal information that we store about you may be linked to the information stored in and obtained from cookies.
		4.Disabling cookies. You can typically remove or reject cookies via your browser settings. In order to do this, follow the instructions provided by your browser (usually located within the “settings,” “help” “tools” or “edit” facility).  Many browsers are set to accept cookies until you change your settings.
		5.Further information about cookies, including how to see what cookies have been set on your computer or mobile device and how to manage and delete them, visit allaboutcookies.org. If you do not accept our cookies, you may experience some inconvenience in your use of our Website. For example, we may not be able to recognize your computer or mobile device and you may need to log in every time you visit our Website.
		6.Pixel tags. We may also use pixel tags (which are also known as web beacons and clear GIFs) on our Website to track the actions of users on our Website. Unlike cookies, which are stored on the hard drive of your computer or mobile device by a website, pixel tags are embedded invisibly on webpages. Pixel tags measure the success of our marketing campaigns and compile statistics about usage of the Website, so that we can manage our content more effectively. The information we collect using pixel tags is not linked to our users’ personal information.
		7.Do Not Track Signals. Some Internet browsers may be configured to send “Do Not Track” signals to the online services that you visit. We currently do not respond to do not track signals. To find out more about “Do Not Track,” please visit allaboutdnt.com.
		
		THE ‘COOKIES’ WE USE
		1.We use cookies for the following purposes:
		1.Authentication – We use cookies to identify you when you visit our website and as you navigate our website;
		2.Status – We use cookies to help us to determine if you are logged into our website;
		3.Personalization – We use cookies to store information about your preferences and to personalize our website for you;
		4.Security – We use cookies as an element of the security measures used to protect user accounts, including preventing fraudulent use of login credentials, and to protect our website and services generally;
		5.Analysis – We use cookies to help us to analyze the use and performance of our website and services; and,
		6.Cookie Consent – We use cookies to store your preferences in relation to the use of cookies more generally.
		
		
		
		
		
		
		
		
		MANAGE YOUR COOKIES
		1.Our Website uses the following types of cookies for the purposes set out below:
		
		Type of Cookie
		
		Purpose
		
		Essential Cookies
		
		These cookies are essential to provide you with services available through our Website and to enable you to use some of its features. Without these cookies, the services that you have asked for cannot be provided, and we only use these cookies to provide you with those services.
		
		Analytics and Performance Cookies
		
		These cookies are used to collect information about traffic to our Website and how users use our Website. The information gathered may include the number of visitors to our Website, the websites that referred them to our Website, the pages they visited on our Website, what time of day they visited our Website, whether they have visited our Website before, and other similar information.  We use this information to help operate our Website more efficiently, to gather broad demographic information and to monitor the level of activity on our Website.
		
		We use Google Analytics for this purpose. Google Analytics uses its own cookies. It is only used to improve how our Website works. You can find out more information about Google Analytics cookies here and about how Google protects your data here.  You can prevent the use of Google Analytics relating to your use of our Website by downloading and installing the browser plugin available here.
		
		Social Media Cookies
		
		These cookies are used when you share information using a social media sharing button or “like” button on our Website or you link your account or engage with our content on or through a social networking website such as Facebook or Twitter. The social network will record that you have done this.
		
		15.Most browsers allow you to refuse to accept cookies and to delete cookies. The methods for doing so vary from browser to browser, and from version to version. You can however obtain up-to-date information about blocking and deleting cookies via these links:
		1.https://support.google.com/chrome/answer/95647?hl=en (Chrome);
		2.https://support.mozilla.org/en-US/kb/enable-and-disable-cookies-website-preferences (Firefox);
		3.http://www.opera.com/help/tutorials/security/cookies (Opera);
		4.https://support.microsoft.com/en-gb/help/17442/windows-internet-explorer-delete-manage-cookies (Internet Explorer);
		5.https://support.apple.com/kb/PH21411 (Safari); and,
		6.https://privacy.microsoft.com/en-us/windows-10-microsoft-edge-and-privacy (Edge).
		16.Blocking all cookies will have a negative impact upon the usability of many websites.
		17.If you block cookies, you will not be able to use all the features on our website.
		
		
		
		SECURITY
		
		1.We recognize our legal obligations to protect the personal information we have gathered about individuals. We have therefore made arrangements to secure against unauthorized access, collection, use, disclosure, copying, modification, disposal or destruction of personal information. These arrangements may include physical security measures, network security measures, and organizational measures such as non-disclosure agreements and need-to-know access.
		
		NOTIFICATION OF LOSS OR UNAUTHORIZED ACCESS OR DISCLOSURE
		1.Where an incident occurs involving the loss of or unauthorized access to or disclosure of personal information under our control, where a reasonable person would consider that there exists a real risk of significant harm to an individual as a result of the loss or unauthorized access or disclosure, we will, without unreasonable delay, provide notice to the Federal Trade Commission (FTC) or any other relevant Federal or State body of the United States of the incident, including any information required by law at the time to be provided to the Commissioner. While United States law provides that the Commissioner has the authority to require us to notify individuals of the unauthorized access or disclosure, we may elect to immediately do so in the event we consider it reasonable in the circumstances. We may also be required to notify the Federal Trade Commission (FTC) or any other relevant Federal or State body of the United States under the Personal Information Protection and Electronic Documents Act (PIPEDA)
		
		REQUESTS FOR ACCESS
		1.United States law permits individuals to submit written requests to us to provide them with:
		1.access to their personal information under the custody or control of Jobsage
		2.information about the purposes for which their personal information under the custody or control of Jobsage has been and is being used; and
		3.the names of organizations or persons to whom and the circumstances in which personal information has been and is being disclosed by Jobsage.
		4.Requests for access are subject to the following:
		1.Any requests must be in writing via post or email;
		2.In order to receive a response to such a request, the individual must provide us with sufficient information to locate their record, if any, and to respond to them;
		3.We will respond to requests in the time allowed by the laws of the United States
		4.We will make a reasonable effort to assist applicants and to respond as accurately and completely as reasonably possible;
		5.All requests may be subject to any fees and disbursements the law permits us to charge; and/or
		6.Where appropriate to do so, we may require advance payment of a deposit or the entire costs of responding to a request for access to personal information.
		
		2.​Please note that an individual’s ability to access his or her personal information under our control is not an absolute right.  United States law provides that Jobsage must not disclose personal information where:
		
		1.the disclosure could reasonably be expected to threaten the safety or physical or mental health of an individual other than the individual who made the request;
		2.the disclosure would reveal personal information about another individual; or
		3.the disclosure would reveal the identity of an individual who has in confidence provided us with an opinion about another individual and the individual providing the opinion does not consent to the disclosure of his or her identity.
		
		3.​​United States law also provides that Jobsage may choose not to disclose personal information where:
		1.​the personal information is protected by any legal privilege;
		2.the disclosure of the information would reveal confidential commercial information and it is not unreasonable to withhold that information;
		3.the personal information was collected by Jobsage for an investigation or legal proceeding;
		4.the disclosure of the personal information might result in similar information no longer being provided to us when it is reasonable that it would be provided;
		5.the personal information was collected or created by a mediator or arbitrator in the conduct of a mediation or arbitration for which he or she was appointed to act
		1.under an agreement,
		2.under an enactment, or
		3.by a court.
		6.the personal information relates to or may be used in the exercise of prosecutorial discretion.
		
		 RESPONSES TO REQUESTS
		1.Our responses to requests for access to personal information will be in writing, and will confirm:
		1.whether we are providing all or part of the requested information;
		2.whether or not we are allowing access or providing copies; and
		3.if access is being provided, when and how that will be given.
		2.If access to information or copies are refused by us, we will provide written reasons for such refusal and the section of FOIA (the Freedom of Information Act) on which that refusal is based.  We will also provide the name of an individual at Jobsage who can answer questions about the refusal, and particulars of how the requesting individual can ask the Information and Federal Trade Commission (FTC) or any other relevant Federal or State body of the United States to review our decision. In order to receive a response to such a request, the individual must provide us with sufficient information to locate their record, if any, and to respond to them.
		
		REQUEST FOR CORRECTION
		1.United States permits individuals to submit written requests to us to correct errors or omissions in their personal information that is in our custody or control. If an individual alleges errors or omissions in the personal information in our custody or control, we will either:
		
		1.correct the personal information and, if reasonable to do so, and if not contrary to law, send correction notifications to any other organizations to whom we disclosed the incorrect information; or
		2.decide not to correct the personal information but annotate the personal information that a correction was requested but not made.
		2.Corrections or amendments will rarely, if ever, be made to opinions, including expert or professional opinions, as opposed to factual information, which may be corrected if in error.
		
		
		AMENDMENT
		1.Jobsage may amend this Policy from time to time as required and without notice, in order to better meet our obligations under the law.
		
		DISPUTES
		1.Governing Law and No Class Proceedings. The laws of the State of South Carolina, and the laws of United States applicable in South Carolina, will govern use of this Agreement and the interpretation, validity and effect of this Agreement, notwithstanding the parties’ physical location (whether permanent or temporary), residence or domicile. The parties agree to not commence any action by way of class proceedings, class action or any other claim involving court proceedings.
		1.Arbitration. The Parties agree that any and all disputes, claims or controversies arising out of or relating to this Agreement that are not resolved by their mutual agreement shall be submitted to final and binding arbitration before Arbitrator of the federal state or its successor, pursuant to the Federal Arbitration Act of United States (FAA). Either Party may commence the arbitration process called for in this Agreement by filing a written demand for arbitration with ADR Chambers of United States, with a copy to the other Party. The arbitration will be conducted in accordance with the provisions of ADR Chambers’ Arbitration Rules in effect at the time of filing of the demand for arbitration. The Parties will cooperate with ADR Chambers and with one another in selecting a single arbitrator from ADR Chambers’ panel of members, and in scheduling the arbitration proceedings. The Parties agree that they will participate in the arbitration in good faith. The provisions of this Section may be enforced by any Court of competent jurisdiction, and the Party seeking enforcement shall be entitled to an award of all costs, fees and expenses, including attorneys’ fees, to be paid by the party against whom enforcement is ordered. The place of arbitration shall be Toronto, Ontario.
		1.The arbitration shall proceed in accordance with the provisions of the Federal Arbitration Act of United States (FAA). The arbitrator shall have the power to proceed with the arbitration and to deliver their award notwithstanding the default by any party in respect of any procedural order made by the arbitrator. It is further agreed that such arbitration shall be a condition precedent to the commencement of any action at law. The decision arrived at by the arbitrator shall be final and binding and no appeal shall lie therefrom. Judgment upon the award rendered by the arbitrator may be entered in any court having jurisdiction.
		2.Arbitration is less formal than a lawsuit in court. Arbitration uses a neutral arbitrator instead of a judge or jury, may allow for more limited discovery than in court, and can be subject to very limited review by courts. Arbitrators can award the same damages and relief that a court can award. This agreement to arbitrate disputes includes all claims arising out of or relating to any aspect of this Agreement, whether based in contract, tort, statute, fraud, misrepresentation, or any other legal theory, and regardless of whether a claim arises during or after the termination of this Agreement.
		
		OUR DETAILS
		1.This website is owned and operated by Jobsage LLP.
		2.We are an South Carolina based LLP of United States.
		3.Our registered address and principal place of business is located at:
		6064 Cloverdale Dr Tega Cay South Carolina, 29708 – United States
		4.You can contact us:
		1.By email, using the email address published on our website from time to time.
		2.If you have any questions with respect to our policies concerning the collection, use, disclosure or handling of your personal information, or if you wish to request access to, or correction of, your personal information under our care and control, or if you are dissatisfied with how we handle your personal information, please contact us at:
		Mail: 6064 Cloverdale Dr Tega Cay South Carolina, 29708 – United States
		Email: SimplyAI@gmail.com
		`
	} 
];

mock.onGet('/api/knowledge-base').reply(config => {
	return [200, knowledgeBaseDB];
});
